### ISSUE TITLE
Switch from fluxbox to another window manager as default?

### ISSUE THREAD

**Issue by mika** [grml/grml-desktop#5]
fluxbox is currently missing in Debian/testing (upcoming bookworm) due to a ftbfs bug (see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=984134). This prompted me to look into the fluxbox situation, especially in Debian, and it doesn't look very promising, tbh. I'm wondering whether we should switch to a different window manager as default and drop fluxbox?

Any opinions? Any preferred window manager alternatives, that fit both in terms of size (not shipping a full desktop environment), but also being newbies friendly? Any volunteers, who might drive this migration?

**Comment by ft** [comment]
Hum. Personally, I usually go with openbox when I don't have time to deploy my normal setup. It's upstream doesn't move very fast and at last I can use it without the need  to look up lots of things in its documentation. Though it feels a little like windowmaker, which I have used a lot in the past. So maybe that's why.

That being said, I don't have a strong opinion this. I do agree, however, that a working windowing system, even if it's not started by default, is important.

**Comment by mika** [comment]
Thanks, @ft - great to hear you're an openbox user, that would have been my suggestion as well! :)

**Comment by ft** [comment]
Well, my actual WM is `xmonad`, but at least for me `openbox` is usable out of the box, no pun intended.

**Comment by mika** [comment]
Alright, fluxbox is still missing from Debian/testing and looks pretty unmaintained in Debian :-/
Time to move on, let's look into migrating to openbox.

**Comment by mika** [comment]
Known todos for switch of fluxbox to openbox:

* adjust `templates/GRML/grml-cheatcodes.txt` in [grml-live](https://github.com/grml/grml-live)
* adjust `etc/grml/fai/config/package_config/XORG` in [grml-live](https://github.com/grml/grml-live)
* adjust screenshots, FAQ etc in [grml.org](https://github.com/grml/grml.org)
* adjust [grml-x](https://github.com/grml/grml-x)

**Comment by mika** [comment]
FTR, while we would consider switching to another window manager, switching wasn't as simple as expected (starting with the tool setting the wallpaper), given that fluxbox is available again, we decided to still ship fluxbox as our default window manager. If anyone wants to improve the desktop situation (also like adjusting fluxbox keybindings (looking at @jkirk :)), switching to another WM,....) please feel free to do so!
